### ISSUE TITLE
Transform cells does not allow Plasmid or Golden Gate inputs

### ISSUE THREAD

**Issue by wrightrc** [klavinslab/aquarium-bugs#53]
Only Gibson Reaction Result and Ligation Product are available in the left side menu of the planner.

**Comment by gasnew** [comment]
Try using Transform Cells from Stripwell. That should allow you to wire to Golden Gate.

**Comment by wrightrc** [comment]
That works for golden gate but I still have no way to transform item 99195 (a plasmid stock) into E. coli in order to propagate and make a new plasmid stock.

**Comment by gasnew** [comment]
That makes sense. @jvrana is on this one!

**Comment by jvrana** [comment]
Fixed! Plasmid Stocks and 1 ng/ul Plasmid stocks are now options! Plasmid stocks will be diluted to 1 ng/ul Plasmid Stocks in the protocol and new item created. The operation will display a warning if this happens and will automatically rewire the input to the new diluted stock. 

Which means, if this happens, the diluted stock will now appear as the input in the planner instead of the plasmid stock you used as an input. This can be changed if its confusing for users.
